# Generated by Django 5.2.7 on 2026-03-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='color_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
