# Generated by Django 5.2.7 on 2026-03-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancetask_brand_maintenancetask_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='color_name',
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='custom_field_definitions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
