# Generated by Django 5.2.7 on 2026-03-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_remove_maintenancetask_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='category',
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='currency',
            field=models.CharField(blank=True, default='Krónur', max_length=3),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
