# Generated by Django 5.2.7 on 2026-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancetask_due_date_maintenancetask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('Living room', 'Living room'), ('Bed room', 'Bed room'), ('Storage', 'Storage'), ('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Office', 'Office'), ('Laundry', 'Laundry'), ('Dining room', 'Dining room'), ('Garden', 'Garden'), ('Hallway', 'Hallway'), ('Other', 'Other')], default='Living room', max_length=50),
        ),
    ]
