# Generated by Django 5.2.7 on 2026-03-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_attachment_user_maintenancetask_user_property_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='currency',
            field=models.CharField(blank=True, default='Krónur', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
