# Generated by Django 5.2.7 on 2026-03-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_vendor_favorite_alter_maintenancetask_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='task_types',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='maintenance.tasktype'),
        ),
    ]
