# Generated by Django 5.2.7 on 2026-03-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_vendor_task_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='task_types',
        ),
        migrations.AddField(
            model_name='vendor',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='maintenance.tasktype'),
        ),
    ]
