# Generated by Django 5.2.7 on 2026-03-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_remove_vendor_task_types_vendor_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='secondary_task_types',
            field=models.ManyToManyField(blank=True, related_name='vendors_secondary', to='maintenance.tasktype'),
        ),
    ]
