# Generated by Django 5.2.7 on 2026-03-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_vendor_secondary_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
