# Generated by Django 5.2.7 on 2026-03-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_maintenancetask_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='finished',
        ),
    ]
