# Generated by Django 5.2.7 on 2026-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_remove_maintenancetask_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='currency',
            field=models.CharField(blank=True, default='Kr.', max_length=3),
        ),
    ]
