# Generated by Django 5.2.7 on 2026-03-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_maintenancetask_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='currency',
            field=models.CharField(blank=True, default='Kr.'),
        ),
    ]
