# Generated by Django 5.2.7 on 2026-03-10 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_alter_maintenancetask_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='final_price_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price including VAT (35% VAT refund eligible)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='vat_refund_claimed',
            field=models.BooleanField(default=False, help_text='Whether 35% VAT refund has been claimed from Icelandic government'),
        ),
    ]
