# Generated by Django 5.2.7 on 2026-03-10 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_maintenancetask_final_price_with_vat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='final_price_with_vat',
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='final_work_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final work price only (35% VAT refund eligible)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
