# Generated by Django 5.2.7 on 2026-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_remove_maintenancetask_final_price_with_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='Breakdown of costs by category with VAT refundable status'),
        ),
    ]
