# Generated by Django 5.2.7 on 2026-03-11 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_maintenancetask_price_breakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetask',
            name='final_work_price',
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='estimated_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
