# Generated by Django 5.2.7 on 2026-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_datashare'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Whether this is a global vendor available to all users'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether this vendor has premium status for search ranking'),
        ),
    ]
