# Generated by Django 5.2.7 on 2026-03-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_vendor_is_global_vendor_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='secondary_task_types',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='task_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='secondary_specialities',
            field=models.ManyToManyField(blank=True, help_text='Secondary specialities/task types', related_name='vendors_secondary', to='maintenance.tasktype'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='speciality',
            field=models.ForeignKey(blank=True, help_text='Main speciality/task type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='maintenance.tasktype'),
        ),
    ]
