# Generated by Django 5.2.7 on 2026-03-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_alter_maintenancetask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershiptransfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
